- styles/nav.less
At certain screen width, navigation menu of the documentation page was hidden behind the main content.
Giving it a fixed width depending on the screen width seems to fix the issue.
Before:
After:
> Fix nav width in the doc page

- content/akeneo-web-api.yaml
- content/responses.md
The status code during a successful deletion of a product should be 204, not 200.
Raised in this issue :  https://github.com/akeneo/pim-docs/issues/560
> Fix status code returned by the deletion of a product

- src/getting-started.handlebars
It is possible to generate the token using the shell, and avoiding to use online website. This PR tells how to do so:
> Add base64 token generation with the shell section

- content/update.md
The documentation about the product values format is a little bit hidden in the Resources section.
I added some redirections to this doc into the Update section, where product values are manipulated and users may ask themselves about this format.
I duplicated the redirections for each use case: Add, modify and erase a product value so that no one miss it.
> Add multiple redirections to the product values format

- content/akeneo-web-api.yaml
- content/responses.md
This PR fix:
- HTTP code 201 and 204 used when patching a resource
- location header returned in 201 and 204 responses
- error message of the error 415 when creating media a media
> Fix error in the api doc about media and code HTTP 201 and 204

- gulpfile.js
- package.json
- src/api-reference/index.handlebars
- src/api-reference/reference.handlebars
- src/documentation.handlebars
- src/getting-started-admin.handlebars
- src/getting-started.handlebars
- src/index.handlebars
- src/partials/layout.handlebars
- tasks/client-documentation.js
- tasks/documentation.js
Initialise the client documentation:
- By adding a PHP client menu
- Refactor the active page mechanism to share the same template "documentation" between php-client and documenation page: first step to not have duplicated code everywhere.
- initialise `client-documentation.js` to download the getting started from github
For now, it's very similar to `documentation.js`.
It has been tested with a part of "category.md" documentation (file not in this PR), and it generates correctly the page:
What's left ?
- Writing all the documentation in the directory `content/php-client`.
- Parsing only a part of the getting-started from github (as Algolia do: the introduction part on github is useless in the documentation).
- some css style I suppose
- refactoring of gulp tasks to be a little bit more …
> Initialise documentation of the PHP client

- content/php-client/authentication.md
- content/php-client/exception.md
- content/php-client/getting-started.md
- content/php-client/http-client.md
- content/php-client/resources.md
- content/php-client/resources/attribute-options.md
- content/php-client/resources/attributes.md
- content/php-client/resources/categories.md
- content/php-client/resources/channels.md
- content/php-client/resources/families.md
- content/php-client/resources/locales.md
- content/php-client/resources/media-files.md
- content/php-client/resources/products.md
- tasks/client-documentation.js
This PR:
- add a getting started (not downloaded from github anymore)
- page on authentication
- page on exception
- page on http client
- concat all resources in one file to avoid big menu
> Add missing part of the documentation of the API

- content/akeneo-web-api.yaml
- tasks/reference.js
Anchors in the reference page are generated based on the url of each endpoint.
We reference these anchors both in this documentation (plain text part) and in some errors that the API throws.
These references are not working anymore because of a [commit](https://github.com/akeneo/pim-api-docs/commit/95d9dbab227df788b311788e0b7de3c9d78352bc) I made, that changed all the urls of all the API endpoints, thus resulting in also changing the reference anchors.
This PR aims at solving this issue. The anchors are now based on a yaml field named `operationId`. This field mimics exactly the name of the previous anchors. All the links to these anchors should work again. No need to modify them.
> Fix anchors in the reference pages

- content/akeneo-web-api.yaml
- src/api-reference/index.handlebars
- src/api-reference/reference.handlebars
This label is displayed in both reference index and in the complete reference.
There are more explanations about the fact that the products endpoints now take into account the EE permissions.
> Add a label on EE endpoints and explanations about EE permissions application

- content/akeneo-web-api.yaml
- content/resources.md
This PR add "attribute_as_image" field for families.
Can be merged when:
- There is versionning in this repository (this is not part of v1.0)
- This PR is merged on master: https://github.com/pierallard/pim-community-dev/pull/11
> [PIM-6291] Add attribute_as_image [DO NOT MERGE NOW]

- src/getting-started.handlebars
The current echo command adds a newline at the end of the string which gets added in the final result, making the full base64 encoded header wrong and unusable.
> Fixes echo command so it generates the right base64 header

- src/getting-started-admin.handlebars
Right now, this command takes only Akeneo 1.7 into consideration:
This documentation is located at the very end of https://api.akeneo.com/getting-started-admin.html
This PR adds the command for Akeneo 2.0 too:
> Fix OAuth client ID and secret generation by CLI

- .gitignore
- content/img/illustrations/illus--Attributeoptions.svg
- content/img/illustrations/illus--Authentication.svg
- content/img/illustrations/illus--Overview.svg
- content/php-client/resources/products.md
- gulpfile.js
- package.json
- readme.md
This PR adds fixes a few glitches and add some improvements on the documentation:
- Add lock files (yarn and npm) to .gitignore
- Use Yarn/NPM to run gulp
- Fix some broken links
- Fix the Gulp watcher
- Add some missing illustration (just a blank SVG) to prevent having an empty rectangle on Firefox
> Doc improvements

- content/rest-api/filter.md
We were not specific enough concerning what was doing the `scope`query parameter when requesting products.
Not only does it filter the product values that are inside one product in order to return only the ones that are from the given channel (+ the non scopable attribute values), but it also only returns the products that are in the tree linked to the given channel.
> More accuracy concerning the scope query parameter on `/products`

- content/rest-api/filter.md
The `locales` filter on the product endpoint won't give you the localised values of an attribute option.
> Be clearer about the locales filter

- src/index.handlebars
> Fix a typo in a link in the homepage

- content/swagger/definitions.yaml
- content/swagger/resources/products/definitions/product.yaml
- content/swagger/resources/published_products/definitions/published_product.yaml
- src/api-reference/reference.handlebars
- src/getting-started.handlebars
Since the 2.1, we have a new key in the `associations` property of the product.
And some fixes of issues I spotted in the hbls template of the reference as well as the swagger spec
> Add product models association to product and fix hbls template

- content/php-client/ce-resources.md
- content/php-client/ee-resources.md
- content/php-client/resources/catalog-modeling-entities/association-types.md
- content/php-client/resources/catalog-modeling-entities/attribute-groups.md
- content/php-client/resources/catalog-modeling-entities/attribute-options.md
- content/php-client/resources/catalog-modeling-entities/attributes.md
- content/php-client/resources/catalog-modeling-entities/categories.md
- content/php-client/resources/catalog-modeling-entities/channels.md
- content/php-client/resources/catalog-modeling-entities/families.md
- content/php-client/resources/catalog-modeling-entities/family-variants.md
- content/php-client/resources/global-settings-entities/currencies.md
- content/php-client/resources/global-settings-entities/locales.md
- content/php-client/resources/global-settings-entities/measure-families.md
- content/php-client/resources/media-resources-entities/asset-categories.md
- content/php-client/resources/media-resources-entities/asset-reference-files.md
- content/php-client/resources/media-resources-entities/asset-tags.md
- content/php-client/resources/media-resources-entities/asset-variation-files.md
- content/php-client/resources/media-resources-entities/assets.md
- content/php-client/resources/media-resources-entities/media-files.md
- content/php-client/resources/product-entities/product-drafts.md
- content/php-client/resources/product-entities/product-models.md
- content/php-client/resources/product-entities/products.md
- content/php-client/resources/product-entities/published-products.md
- tasks/client-documentation.js
The menu of client resources was too long. On some small screen, the end of the menu was not even accessible.
This PR reorganises it in several main sections for better readability.
**Before**
**After**
> Rework client resources organisation

- content/php-client/getting-started.md
It was missing into the documentation.
> Add compatibility matrix doc for the PHP client

- content/rest-api/resources.md
- content/swagger/resources/product_models/routes/product_models.yaml
- content/swagger/resources/product_models/routes/product_models_code.yaml
- content/swagger/resources/products/routes/products.yaml
- content/swagger/resources/products/routes/products_code.yaml
In Swagger:
- Add description to say that user groups permissions are now applied on product models.
- Add description to say that in some cases, you might create draft when updating product models.
In Resources section of the plain API doc:
- Add the metadata field which is new into the product model format.
> Draft creation and metadata are new in PM since 2.3

- content/rest-api/resources.md
I'm proposing to remove the warning `An attribute cannot be both localizable and locale specific at the same time.` 
Presumably this statement was valid for earlier Akeneo versions, but with 2.3 you can have an attribute that is both localizable and locale specific.
Another option would be to change the text to 'An attribute **can** be both localizable and locale specific at the same time.', but I see no value in this statement, it seems to be intuitive.
> Remove outdated warning about localizable attributes

- content/rest-api/security.md
https://api.akeneo.com/documentation/security.html#get-a-token
```
To get a valid token, the client application must send the following request:
curl -X POST http://your-host/api/oauth/v1/token \
-H "Content-Type: application/json" \
-H "Authorization: Basic YOUR_BASE_64_CLIENT_ID_AND_SECRET" \
-d '{
"grant_type": "password",
"username": your_username,
"password": your_password
}'
```
Cause an error 400 invalid json content because it don't have double quote between his username and password.
The example right after is correct (cf https://api.akeneo.com/documentation/security.html#example):
```
[...]
-d '{
"grant_type": "password",
"username": "peter",
"password": "peter4ever"
}'
```
> Fix get a token request that cause invalid json response

- content/php-client/getting-started.md
The "http-interop/http-factory-guzzle" is needed especially on frameworks like Laravel. If you don't add this you get an error like this:
````
No PSR-17 request factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation
````
> Adding http-interop/http-factory-guzzle in the installation part

- tasks/build-doc.js
The link to this part of the documentation was broken because of an uppercase issue.
> Fix link to Why the API

- tasks/reference.js
The 3.2 version of the reference was not generated at all.
> Fix the switcher for 3.2

- content/php-client/resources/products/product-media-files.md
> Fix a typo in the documentation of the PAI about downloading a media file

- Makefile
> Generally we use docker run -it --rm -u "$${UID}":"$${GID}" to set the UID/GID with docker to use the same id/gid as the host. But if you use Makefile + circle ci, be careful. It uses sh , symlink to dash on Ubuntu. There is no variable such as UID/GID set. So, this trick does not work. If you use bash, it set the UID to 1001 on Circle CI. And commands are failing most of the time as there is no user with id 1001 in the docker container.
By sharing `/etc/passwd`, it works correctly. We have to set `HOME` variable too, otherwise yarn tries to find a file in `/home/circleci/.yarnrc` and this directory does not exist.
> Set correctly ui/gid in the container

- Makefile
Fix deployment step, because nightly build failed:
https://app.circleci.com/pipelines/github/akeneo/pim-api-docs/414/workflows/eb35a1bc-0fb4-4d83-a923-53444ee25267/jobs/441
It's due to my fix on uid/gid. CI was green as deployment step is not executed.
> Rsync needs an existing user to work

- content/events-api/security.md
- tasks/build-doc.js
I had to add a blank line at the beginning of the PHP snippets to avoid a strange behavior where the indentation was not correct.
> CXP-613: request signature check documentation

- content/php-client/resources/reference-entity/attributes.md
- content/swagger/resources/association_types/definitions/association_type.yaml
Fix 2 documentation issues: https://akeneo.atlassian.net/browse/API-1417 
In the PHP client documentation, replace 
```
'localizable' => true,
'scopable' => true,
```
by
```
'value_per_locale' => false,
'value_per_channel' => false,
```
AND
add (Only available in Serenity version) on quantified association parameters.
> API-1417 Update is_quantified and is_two_way documentation.

- content/events-api/security.md
Fix the `$requestBody` example that was misleading.
> Fix security example of the events api

- content/rest-api/pagination.md
This fix addresses `searchAfter` typo in the example on this page
https://api.akeneo.com/documentation/pagination.html#the-search-after-method
> Fixed searchAfter example typo

- content/concepts/products.md
API-1572: fixed typos and updated data descriptions found in products
Corrected typos found on product concept page:
- Date example now displays correct date value
- Metric description now matches with the provided example
- Price description now matches with the updated example
> API-1572: fixed typos and updated data descriptions found in products

- content/img/illustrations/illus--System.svg
> fix illus--System.svg 404 not found

- content/rest-api/filter.md
For updated date filter, variant inherits from parents
https://api.akeneo.com/documentation/filter.html#on-their-creation-or-update-date
> Add details for Products updated date filter

- content/rest-api/update.md
The original resource in the Rule 3 (VALIDATION ON DATA TYPES) has
"parent": **"master"**
The patch body is empty and therefore, according to the rule, the resulting resource MUST NOT change.
However, the resulting resource in the example has a modified parent
"parent": **"clothes"**
This PR fixes the problem and keeps the initial parent intact.
> Fix the example in Rule 3 to match with actual behavior

- .github/CODEOWNERS
According to the latest ownership distribution of the features, https://www.notion.so/akeneo/Apps-66d9ceddf4324341a156cdda79c1f1a3, all pages regarding the App Documentation are owned and maintained by the octopus.
The `CODEOWNERS` configuration will ensure that any PR on the App documentation must be approved by at least one Octopus to be merged.
> Add CODEOWNERS on Apps documentation

- Makefile
The last Alpine Linux being used for the Docker image, it provides a recent version of SSH, where RSA support is disabled.
> Works around RSA disabling on recent SSH version

- content/rest-api/authentication.md
::: info
By default, the refresh token expiration is set at 1209600 seconds (14 days).
:::
> refresh token duration

- content/concepts/products.md
https://api.akeneo.com/concepts/products.html#boolean-attribute
Data field should contain either true or false, but a string is given in the example.
> Remove string from boolean attribute update

- content/rest-api/filter.md
Add documentation to using the "IN" and "NOT IN" filters to the product-models search
> CPM-1139: Add doc ProductModel in list

- content/mapping/product/0.3.0/schema
Added new version `0.3.0` for catalogs meta-schema and updated schema example.
> CXP-1639: add mapping meta-schema v0.3.0

- tasks/build-doc.js
Remove and reorganize links on the app-portal menu
> deploy: remove useless links

- content/swagger/paths.yaml
- src/api-reference/index.handlebars
- src/api-reference/reference.handlebars
- tasks/reference.js
The PR is deployed on https://pr-899.api-dev.akeneo.com/
> [CPM-1674] Update API doc to encourage users to use Product UUID endpoint

- .circleci/config.yml
**Description**
Current image used is deprecated. 
`ubuntu-2204:2022.07.1` => `ubuntu-2204:current`
> Update docker image for CI jobs

- content/rest-api/overview.md
Be more specific about the limitations and provide guidance on strategies to handle it.
Also, I made the "retry-after" not a requirement for 429, as some security layers in our stack doesn't provide this header.
> Improve documentation about fair usage on ou API

- deployments/modules/services/networking/backend-bucket.tf
```
➜  pim-api-docs git:(CHA-937-disable-indexing-of-non-production-environments-for-pim-api-documentation) curl --head https://pr-946.api-dev.akeneo.com                       
HTTP/2 200 
date: Fri, 20 Sep 2024 10:41:20 GMT
last-modified: Fri, 20 Sep 2024 10:29:19 GMT
etag: "48fa2a79b5f66af7eab001b962f30daa"
x-goog-generation: 1726828159705456
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 40386
x-goog-meta-goog-reserved-file-mtime: 1726828006
content-type: text/html
x-goog-hash: crc32c=jabFDw==
x-goog-hash: md5=SPoqebX2avfqsAG5YvMNqg==
x-goog-storage-class: STANDARD
accept-ranges: bytes
content-length: 40386
x-guploader-uploadid: AD-8lju7-AgZUCN3TKd3rg4YNv-qWj9TPwIGK874O7mK3_lTeMMymQk9CRxhG4cX84j8l7PD9eg
server: UploadServer …
```
> fix(cha-937): disable indexing of non-production environments

- deployments/modules/services/networking/load-balancer.tf
api.akeneo.com uses TLS 1.0 and TLS 1.1 which are now deprecated.
This PR force the use of TLS 1.2 for api.akeneo.com
- Create a new default SSL policy with TLS 1.2 and [COMPATIBLE](https://cloud.google.com/load-balancing/docs/ssl-policies-concepts#profilefeaturesupport:~:text=Allows%20the%20broadest%20set%20of%20clients%2C%20including%20clients%20that%20support%20only%20out%2Dof%2Ddate%20SSL%20features%2C%20to%20negotiate%20SSL%20with%20the%20load%20balancer.) profile (Allows the broadest set of clients to not reject potentials out-of-date SSL clients)
- Link the load balancer to use this default SSL policy
Testing:
Using `docker run --rm -it nablac0d3/sslyze`
Before: 
After:
No more TLS version error.
> PIM-12026 [Security] Add SSL policy to use only TLS 1.2

- content/events-api/migrate-to-event-platform.md
- tasks/build-doc.js
Preview here : https://pr-1021.api-dev.akeneo.com/events-documentation/migrate-to-event-platform.html
> CHA-1422: Guide to migrate from Event API to Event Platform

- content/event-platform/concepts.md
- content/event-platform/key-platform-behaviors.md
Whats changed:
1. Info pane to suggest using the queuing subscription type form
2. Delivery rate policy clarification
> CHA-1452 Event-Platform Update http subscription delivery policy

- content/event-platform/limitations.md
- content/graphql/limitations.md
- content/rest-api/limitations.md
- tasks/build-doc.js
- Move REST API Limitations and fair usage details to a dedicated page named "Limitations" (as it is done for Event Platform and GraphQL)
- Add a link to this page in GraphQL limitations page
- Change the quota wording in Event Platform to remove the 5M "fake" limit.
> Several changes on quotas and limitations

- content/event-platform/available-events.md
I generated it from asyncapi spec in event platform, but didn't copy past the file as it is.
Indeed, there were direct changes done on the file in this repository...
For example, this event does not exist in the event platform spec: https://github.com/akeneo/pim-api-docs/pull/1013/files
> Add doc for completeness event

- .circleci/config.yml
- content/apps/overview.md
- content/extensions/getting-started.md
- content/graphql/limitations.md
- tasks/copy-assets.js
Before this PR, when we deleted a page, the deletion was not propagated to the bucket that store the deployed files.
While adding the option that force the deletion of unmatching files, I restore some important files like fonts that are still used.
> CHA-1625: sync with deletion the pim-api-doc bucket (clean up non used files)
