akeneo/pim-api-docs

- src/index.handlebars
> Add missing link in the home page

- content/akeneo-web-api.yaml
- src/api-reference/reference.handlebars
2 endpoints are missing from the API reference.
Here they are !
> Add authentication and overview endpoints in ref

- src/api-reference/index.handlebars
- src/api-reference/reference.handlebars
- src/documentation.handlebars
- src/getting-started-admin.handlebars
- src/getting-started.handlebars
- src/index.handlebars
- src/partials/contrib-footer.handlebars
- styles/landing-page.less
- tasks/reference.js
- The "handlebars" files are not well indented, particularly on handlebars tag. This PR fix that.
I didn't found a good indentation plugin with phpstorm, so I did it automatically + fix it manually.
I didn't modify the code, except for some unclosed tags (2/3).
- Also, I've used partial block to include the footer about contribution.
- I've renamed every "ressource" in the code by "resource".
- And, last but not least, an amazing improvement about the UI: response headers have the same style as the request headers.
> Fix indentation for the template files + some refactoring

- content/akeneo-web-api.yaml
- src/api-reference/index.handlebars
- src/api-reference/reference.handlebars
- styles/label.less
- styles/panel.less
- styles/typography.less
- styles/variables.less
- tasks/reference.js
Add a switch to be able to filter the endpoints from the PIM 1.7 and the PIM 2.0
> Add versions

- content/filter.md
- content/overview.md
- content/pagination.md
- content/php-client/introduction.md
- content/resources.md
- content/security.md
- src/getting-started-admin.handlebars
- New UI to handle API connections
- Explanation about the new entities in 2.0 of the API
- New API ACLs for the new entities
- Change command lines with `app` to `bin` for to 2.0
- API PHP client will soon be released, no more Beta tag on it
> Update REST API, PHP client and getting started according to what's new in v2

- content/akeneo-web-api.yaml
> Last update to the Swagger spec

- content/files/Akeneo PIM API.postman_collection.json
Cannot be installed because missing id.
> Fix postman collection

- content/files/Akeneo PIM API.postman_collection.json
- Product models & family variants new endpoints in 2.0.1
- Fix a few typos in other endpoints description
> Update the Postman collection with the last endpoints

- content/files/Akeneo PIM API.postman_collection.json
New version of the collection (we use collection 2.1 now). That's why there are so many changes.
> Postman coll

- content/php-client/resources/products.md
there is a missing quote sign in the example code snippet
> add quote to code snippet

- content/files/Akeneo PIM API.postman_collection.json
- content/swagger/resources/families/definitions/family.yaml
- content/swagger/resources/families/definitions/family_variant.yaml
- content/swagger/resources/families/routes/families.yaml
- content/swagger/resources/families/routes/families_code_variants.yaml
- content/swagger/resources/families/routes/families_code_variants_code.yaml
Postman collection seems to change the order off the endpoint... Maybe an update of postman :/
> Api 463 : add patch on a list of family variants/ patch on single family variant

- src/api-reference/reference.handlebars
In both:
- the request body of POST/PATCH endpoints
- the response body of GET endpoints
> Fix Handlebars to handle more json formats

- content/rest-api/security.md
- content/swagger/resources/token.yaml
Do not merge it before merge 1.7 into 2.0.
> API-216: support the content-type application/x-www-form-urlencoded when getting a token

- content/php-client/ce-resources/products.md
As there is no endpoint in the API to create a draft (it is automatically done in EE when updating a product you don't own), this PR introduce an explanation about when (under what conditions) a user will create a draft.
>  API-422: Create a product draft 

- content/php-client/ee-resources/product-drafts.md
Update according to last EE client changes
> API-423: Update draft submission

- styles/nav.less
> Update the navigation style according to the helpcenter

- content/rest-api/filter.md
I added a hint about what time zone is used when using date filters.
> Added hint about timezone in date filters

- content/swagger/resources/assets/routes/assets_code_reference_files_channel_code_locale_code.yaml
- content/swagger/resources/assets/routes/assets_code_variation_files_channel_code_locale_code.yaml
- content/swagger/resources/media_files/routes/media_files.yaml
- content/swagger/resources/token.yaml
- src/api-reference/reference.handlebars
Ability to post media files on product model.
> Add doc for new feature

- content/swagger/resources/media_files/routes/media_files.yaml
- content/swagger/resources/token.yaml
- src/api-reference/reference.handlebars
Already done on master, this is the backport in 2.0.
> Add media file on product models

- src/getting-started-admin.handlebars
- src/getting-started-postman-collection.handlebars
- src/getting-started.handlebars
Add precision on versions in the getting started guides.
> Add precision on versions

- content/php-client/getting-started.md
> Fix links of the PHP client getting started

- content/files/Akeneo PIM API.postman_collection.json
There was a wrong property in the channel format for the PATCH.
This PR removes it.
> remove yo property

- content/files/Akeneo PIM API.postman_collection.json
I updated the collection with the new endpoints available in 2.3
> Add new endpoints in Postman collection

- src/api-reference/index.handlebars
- src/api-reference/reference.handlebars
- tasks/reference.js
In the index of the reference and the reference itself.
> Add 2.3 in the dropdown of versions

- src/getting-started-admin.handlebars
- src/getting-started-postman-collection.handlebars
- src/getting-started.handlebars
During the Summer session, one of our team worked on making the Postman collection easily working with our demo instance. 
Here is an update of the documentation to give some pointers to this demo instance.
> Add mentions to the demo instance

- content/rest-api/overview.md
- content/swagger/resources/reference_entity_attributes/definitions/reference_entity_attribute_options.yaml
- content/swagger/resources/reference_entity_attributes/routes/reference_entity_attributes_code_options.yaml
- content/swagger/resources/reference_entity_attributes/routes/reference_entity_attributes_code_options_code.yaml
I created a new PR because the last one was totally broken (horrible merge to do).
> PIM-7808-7809: Upsert one or several ref entity attribute options

- content/swagger/resources/reference_entity_records/routes/reference_entity_records.yaml
> Rename main_image into image

- content/rest-api/resources.md
- content/swagger/resources/reference_entity_records/definitions/reference_entity_record.yaml
- content/swagger/resources/reference_entity_records/definitions/reference_entity_records.yaml
The new record format was not up to date everywhere. This PR fixes this.
> Fix the record format

- content/rest-api/filter.md
> Get the variants of a given product model

- content/rest-api/filter.md
Reverts akeneo/pim-api-docs#268
> Revert "Get the variants of a given product model"

- content/swagger/resources/reference_entity_attributes/definitions/reference_entity_attribute.yaml
Add number attribute type reference entities in Definitions
> [DO NOT MERGE] 3.2- Add number attribute type reference entities Def

- content/swagger/resources/attributes/definitions/attribute.yaml
> Fix attr price name

- content/guides/dam-connection/pre-requisites.md
New edits. I think information on line 3 is worth sharing in introduction.md as well!
> Update content for pre-requisites.md

- content/guides/dam-connection/synchronize-assets.md
> Update synchronize-assets.md content

- .circleci/config.yml
- Makefile
- README.md
- tasks/deploy.js
(note: the workflow in the picture is just to test that each step is working as expected, it will not be the same one for PR or master branch)
It means that master is the production. If you want to add new endpoint for a future release but not publishing it, you have to do a feature branch or hide it (as for the PIM).
> Initialize a circle CI workflow

- content/concepts/asset-manager.md
- content/img/concepts/asset-family-for-transformation.svg
Bad link to illus and add new illus for the transformations
> Add illus transfo

- content/guides/dam-connection/synchronize-assets.md
- content/guides/dam-connection/technical-stack.md
- content/rest-api/troubleshooting.md
> Fix dead link

- content/guides/dam-connection/pre-requisites.md
- "attribute as main media" for family
- type properties for media link, media file
> Add some information for premium connectors.

- content/php-client/resources/target-market-settings/measure-families.md
- content/php-client/resources/target-market-settings/measurement-families.md
> MET-185: Add documentation for measurement families in the phpclient

- content/rest-api/filter.md
| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | no
| Added Behats                      | no
| Changelog updated                 | no
| Review and 2 GTM                  |  no
| Migration scripts                 | no
| Tech Doc                          | yes
An error has crept into an example.
> fix api-rest filter example

- content/guides/translation-connection/step2-understand-akeneo-pim.md
- content/guides/translation-connection/step3-how-to-build-your-connector.md
- content/guides/translation-connection/step4-known-limits.md
New Playbook on how to develop a Translation connector with our API.
> Translation connector

- content/concepts/catalog-structure.md
See https://github.com/akeneo/pim-api-docs/pull/404
> Add missing concept for attr

- content/guides/translation-connection/step3-how-to-build-your-connector.md
* Add information for simple and multi select
* Simplify configuration to select text attributes
* Explain Agile approach
> Modification from Nathalie and Romain's feedbacks.

- content/events-reference/events-reference-serenity/product-models.md
- content/events-reference/events-reference-serenity/resources/product-model-updated.yml
- content/events-reference/events-reference-v5/product-models-50.md
- content/events-reference/events-reference-v5/resources/product-model-updated-50.yml
add API reference cheat sheet for product model updated event
> API-1370: API reference cheat sheet for product model updated event

- content/events-reference/events-reference-serenity/product-models.md
- content/events-reference/events-reference-serenity/resources/product-model-created.yml
- content/events-reference/events-reference-v5/product-models-50.md
- content/events-reference/events-reference-v5/resources/product-model-created-50.yml
Add API reference cheat sheet for product model created event
> API-1369: API reference cheat sheet for product model created event

- content/events-reference/events-reference-serenity/product-models.md
- content/events-reference/events-reference-serenity/resources/product-model-removed.yml
- content/events-reference/events-reference-v5/product-models-50.md
- content/events-reference/events-reference-v5/resources/product-model-removed-50.yml
Add API reference cheat sheet for product model removed event
> API-1368: API reference cheat sheet for product model removed event

- content/events-reference/events-reference-serenity/products.md
- content/events-reference/events-reference-serenity/resources/product-created.yml
- content/events-reference/events-reference-v5/products-50.md
Add API reference cheat sheet for product created event
> API-1365: API reference cheat sheet for product created event

- content/events-reference/events-reference-serenity/products.md
- content/events-reference/events-reference-serenity/resources/product-removed.yml
- content/events-reference/events-reference-v5/products-50.md
API reference cheat sheet for product removed event
> API-1367: API reference cheat sheet for product removed event

- src/index.handlebars
> home page update - add events api ref.

- content/concepts/asset-manager.md
- content/concepts/catalog-structure.md
- content/concepts/products.md
- content/concepts/reference-entities.md
- content/concepts/target-market-settings.md
- content/files/akeneo-PIM-API-environment-4x.postman_environment.json
- content/getting-started/connect-the-pim-4x/step-1.md
- content/getting-started/connect-the-pim-4x/step-3.md
- content/getting-started/connect-the-pim-4x/welcome.md
- content/getting-started/connect-the-pim-old/step-2.md
- content/getting-started/connect-the-pim-old/welcome.md
- content/getting-started/your-first-tutorial-4x/step-1.md
- content/getting-started/your-first-tutorial-4x/step-2.md
- content/getting-started/your-first-tutorial-4x/welcome.md
- content/getting-started/your-first-tutorial-old/step-2.md
- content/getting-started/your-first-tutorial-old/welcome.md
- content/guides/ecommerce-connection/step1-who-does-what.md
- content/guides/syndication-connection/step1-who-does-what.md
- content/php-client/introduction.md
- content/rest-api/authentication.md
- content/rest-api/filter.md
- content/rest-api/update.md
- src/api-reference/index.handlebars
- src/api-reference/reference.handlebars
- src/index.handlebars
- src/partials/getting-started.handlebars
- tasks/build-doc.js
- tasks/reference.js
Add the 5.0 in the version list available on the Concepts page: 
And update some parts of the documentation.
I.e.
> 5.0 version addition

- content/events-api/overview.md
- content/events-api/security.md
- content/events-api/subscription.md
- content/events-reference/events-reference-serenity/resources/product-created.yml
- content/events-reference/events-reference-serenity/resources/product-model-created.yml
- content/events-reference/events-reference-serenity/resources/product-model-removed.yml
- content/events-reference/events-reference-serenity/resources/product-model-updated.yml
- content/events-reference/events-reference-serenity/resources/product-removed.yml
- content/events-reference/events-reference-serenity/resources/product-updated.yml
- Some suggestions on the content of the events api documentation
- Fix the event api format (was missing the key `resource`)
> CXP-641 update events api documentation

- content/swagger/resources/published_products/definitions/published_product.yaml
Updating documentation on published products & associations with quantities
> Update published products and quantified_associations

- content/rest-api/authentication.md
CURL command format was incorrect
> Changed refresh token documentation

- content/rest-api/filter.md
Add documentation of the filter to get root or non-root categories only.
> API-1565: add "is_root" search filter

- content/events-api/more-about-events.md
New paragraph to explain how we manage EE permission application to send or not a product event.
> Add a paragraph about EE permission application on events

- content/rest-api/authentication.md
The current ones are not in phase with auto generated slugs from titles
> Fix sections links

- content/rest-api/filter.md
> API-1596: add to asset search endpoint new operators on updated property

- content/rest-api/overview.md
- content/rest-api/responses.md
Adding some documentation on 429 Too Many Requests when API usage exceed rate limit threshold.
> adding doc on 429

- content/rest-api/overview.md
- content/rest-api/responses.md
Fix English according Rémy and Adrien reviews
> Fix english

- content/concepts/asset-manager.md
Remove CMYK from possible colorspace transformations
https://api.akeneo.com/concepts/asset-manager.html#change-of-colorspace
> Remove CMYK from transformation #3

- content/apps/introduction.md
- gulpfile.js
- src/partials/apps.handlebars
- src/partials/layout.handlebars
- styles/layout.less
- styles/variables.less
- tasks/build-doc.js
> CXP-930: Apps introduction

- content/apps/create-app-in-php.md
- content/apps/create-app.md
- content/apps/introduction.md
- content/apps/using-oauth2.md
- tasks/build-doc.js
> CXP-933: draft tuto for creating an App

- content/rest-api/pagination.md
Update hyperlink on "Search-after method" on this paragraph: https://api.akeneo.com/documentation/pagination.html#the-offset-method
> Update hyperlink on "Search-after method"

- content/apps/access-scopes.md
> add authentication scopes

- content/rest-api/filter.md
https://api.akeneo.com/documentation/filter.html#available-operators
> Delete ENDS WITH operator as it's not supported

- content/apps/how-to-have-public-url-for-my-app.md
- tasks/build-doc.js
> CXP-1075 Added doc on how to have public url for an app

- content/php-client/getting-started.md
- content/php-client/introduction.md
- content/php-client/resources/PAM/asset-categories.md
- content/php-client/resources/PAM/asset-reference-files.md
- content/php-client/resources/PAM/asset-tags.md
- content/php-client/resources/PAM/asset-variation-files.md
- content/php-client/resources/PAM/assets.md
- content/php-client/resources/asset-manager/asset-attribute-options.md
- content/php-client/resources/asset-manager/asset-attributes.md
- content/php-client/resources/asset-manager/asset-families.md
- content/php-client/resources/asset-manager/asset-media-files.md
- content/php-client/resources/asset-manager/assets.md
- content/php-client/resources/products/product-drafts.md
- content/php-client/resources/products/product-model-drafts.md
- content/php-client/resources/products/product-models.md
- content/php-client/resources/products/products.md
- content/php-client/resources/products/published-products.md
- content/php-client/resources/reference-entity/attribute-options.md
- content/php-client/resources/reference-entity/attributes.md
- content/php-client/resources/reference-entity/media-files.md
- content/php-client/resources/reference-entity/records.md
- content/php-client/resources/reference-entity/reference-entities.md
Related to https://github.com/akeneo/api-php-client-ee/pull/105 & https://github.com/akeneo/api-php-client/pull/223
> API-1729: Update dedicated client documentation to drop EE support

- content/rest-api/filter.md
- content/swagger/resources/product_models/routes/product_models_code.yaml
- content/swagger/resources/system_information.yaml
> v6 updates

- content/rest-api/permissions.md
Document ACLs we added on asset families, assets, reference entities, and records.
> Endpoint access restrictions update

- src/api-reference/reference.handlebars
https://akeneo.atlassian.net/browse/API-1759
> fix(API-1759): Add 6.0 in version list of REST API docs

- content/rest-api/filter.md
related to https://akeneo.atlassian.net/browse/API-1638
> feat(api-1638): Improve the update filter on Ref. entity records

- content/rest-api/filter.md
https://api.akeneo.com/documentation/filter.html#
> Add that Serenity servers are in UTC time zone ofr filters not using ISO 8601 format

- .circleci/config.yml
So the label in github has a meaning
> ci(): Replace 'destroy_staging?' job step by 'deploy_staging?'

- content/files/Akeneo PIM API.postman_collection.json
> feat(api-1652): update postman collection

- src/api-reference/reference.handlebars
https://akeneo.atlassian.net/browse/API-1753
> feat(API-1753): Description on API resource parent nodes

- content/php-client/resources/catalog-structure/attribute-options.md
Fixes
- https://github.com/akeneo/api-php-client-ee/issues/99
- https://github.com/akeneo/api-php-client/issues/175
> fixed fault in code snippet of Upsert a list of attribute options

- content/php-client/resources/asset-manager/asset-families.md
- content/php-client/resources/asset-manager/assets.md
Fixes #385
https://akeneo.atlassian.net/browse/API-1797
> fix(API-1797): Dead links in PHP Client Asset resources

- content/concepts/products.md
> Reference data deprecated

- content/rest-api/filter.md
> add the IN operator on product identifiers

- content/apps/how-to-test-my-app.md
Fixes #572
https://akeneo.atlassian.net/browse/API-1799
> fix(1799): Switch 'Setting' to 'System'

- content/apps/using-oauth2.md
> OCT-10 Add a token error response example

- content/apps/using-oauth2.md
- content/apps/why-apps-over-connectors.md
- content/getting-started/connect-the-pim-4x/step-2.md
- content/getting-started/connect-the-pim-old/step-1.md
- content/guides/translation-connection/step3-how-to-build-your-connector.md
- src/index.handlebars
App store domain has moved from marketplace.akeneo.com to apps.akeneo.com.
This PR changes all the links related to marketplace to apps.
> MW-368 update app store url from marketplace to apps

- content/apps/create-app.md
- content/apps/create-app/activate-java.md
- content/apps/create-app/callback-java.md
https://akeneo.atlassian.net/browse/API-1791
> Api 1791 documentation create code snippets in different languages - JAVA

- content/getting-started/events-api-best-practices-5x/welcome.md
https://akeneo.atlassian.net/browse/API-1857
Fixes #573
> fix(API-1857): Dead link to Event API guide

- content/files/Akeneo PIM API.postman_collection.json
- content/rest-api/filter.md
https://github.com/akeneo/pim-enterprise-dev/pull/14097
> API-1803 & API-1804: Filter Asset & Reference Entity by codes

- content/php-client/introduction.md
- tasks/build-doc.js
https://akeneo.atlassian.net/browse/API-1865
> PHP client doc: add Introduction page to table of content

- src/partials/layout.handlebars
Update credentials for Algolia
> Fix Algolia application ID and API Key

- content/mapping/product/0.0.1/schema
- tasks/copy-assets.js
see https://github.com/akeneo/pim-community-dev/pull/17982
> CXP-1300: add first mapping

- content/getting-started/from-identifiers-to-uuid-7x/welcome.md
Changing a deprecated date mention in the text.
> UUID endpoint release date update

- content/concepts/products.md
- content/getting-started/connect-the-pim-4x/step-2.md
- content/guides/erp-connection/step1-who-is-your-app-intended-for.md
- content/guides/erp-connection/step3-understand-akeneo-pim.md
Hi,
I was reading through the documentation and stumbled across some spelling mistakes. Here's my proposal for correcting them.
> Fix some typos / grammar issues

- content/apps/catalogs.md
- content/files/Akeneo PIM API.postman_collection.json
- tasks/build-doc.js
- tasks/reference.js
Since (beta) is displayed on Apps doc, I thought it would be consistent to display it everywhere else
> Add more beta disclaimers for App catalogs

- content/rest-api/pagination.md
> fix(API-1852): Update API rest pagination offset section

- content/guides/erp-connection/introduction.md
Fix broken image: naming modification.
> Update introduction.md on ERP guide: fix a broken image

- content/mapping/product/0.0.2/schema
Added mapping containing special constraint on UUID property field
> CXP-1334: Added mapping 0.0.2

- content/getting-started/from-identifiers-to-uuid-7x/welcome.md
Mostly updated dates and chronology as sku optional has now been released
> Updates following optional sku launch

- content/apps/catalogs.md
- content/swagger/parameters.yaml
- content/swagger/paths.yaml
- content/swagger/resources/app_catalogs/routes/app_catalogs.yaml
- content/swagger/resources/app_catalogs/routes/app_catalogs_id.yaml
- content/swagger/resources/app_catalogs/routes/app_catalogs_id_product_uuids.yaml
- content/swagger/resources/app_catalogs/routes/app_catalogs_id_products.yaml
- content/swagger/resources/app_catalogs/routes/app_catalogs_id_products_uuid.yaml
- content/swagger/responses.yaml
- clean up of the documentation related to catalog endpoints
- add information about disabled catalogs
> Catalog documentation cleanup

- content/tutorials/guides/how-to-get-your-app-token.md
- content/tutorials/guides/how-to-retrieve-pim-structure.md
- src/partials/guided-tutorials.handlebars
- styles/guided-tutorial.less
https://akeneo.atlassian.net/browse/API-1947
> feat(API-1947): Add 'All guided tutorials' button in each guided tutorials

- content/apps/create-app/activate-nodejs.md
- content/apps/create-app/callback-nodejs.md
- content/tutorials/guides/how-to-get-families-and-attributes.md
- content/tutorials/guides/how-to-retrieve-pim-structure.md
> fix snippet line length & misc

- content/tutorials/guides/how-to-get-families-and-attributes.md
- content/tutorials/guides/how-to-get-pim-product-information.md
- tasks/build-doc.js
https://akeneo.atlassian.net/browse/API-1905
https://akeneo.atlassian.net/browse/API-1901
> API-1943: add guided tutorial collect product information to documentation

- components/block-welcome.css
- components/block-welcome.html
- components/components.css
- components/components.html
- content/tutorials/guides/how-to-collect-product-variations.md
- content/tutorials/guides/how-to-get-families-and-attributes.md
- content/tutorials/guides/how-to-get-pim-product-information.md
- content/tutorials/guides/how-to-get-your-app-token.md
- content/tutorials/guides/how-to-retrieve-pim-structure.md
- styles/guided-tutorial.less
https://akeneo.atlassian.net/browse/API-1977
> API-1977: Make Requirement and Welcome block layouts responsive

- components/components.css
- components/components.html
- content/tutorials/guides/how-to-get-families-and-attributes.md
- content/tutorials/guides/how-to-get-pim-product-information.md
- content/tutorials/guides/how-to-retrieve-pim-structure.md
- styles/guided-tutorial.less
https://akeneo.atlassian.net/browse/API-1978
> API-1978: Make regular Next Step block layout responsive

- styles/anchor.less
- styles/nav.less
- styles/variables.less
https://akeneo.atlassian.net/browse/API-1974
> API-1974: Lower the subtitles anchor results display under the search bar

- content/tutorials/guides/how-to-collect-product-variations.md
- content/tutorials/guides/how-to-get-pim-category-tree.md
- src/partials/layout.handlebars
- tasks/build-doc.js
https://akeneo.atlassian.net/browse/API-1907
https://akeneo.atlassian.net/browse/API-2008
https://github.com/akeneo/php-guided-tutorials/pull/8
https://github.com/akeneo/js-guided-tutorials/pull/7
> API-2008: Add new 'How to get PIM category tree' guided tutorial

- components/components.css
- styles/guided-tutorial.less
https://akeneo.atlassian.net/browse/API-1908
> API-1969: 'Develop your App' button vertical alignment

- content/guides/syndication-connection/step3-define-your-first-scope.md
Update dead link in step3-define-your-first-scope.md
> Update dead link

- content/news/2022.md
> Add December updates

- content/mapping/product/0.0.3/schema
New version of JSON Meta Schema for app catalogs, allowing number and boolean attribute types.
> CXP-1287: JSON Meta Schema V0.0.3

- content/mapping/product/0.0.4/schema
New version of JSON Meta Schema for app catalogs, allowing a new key "format".
> CXP-1375: JSON Meta Schema V0.0.4

- content/mapping/product/0.0.5/schema
A new version of the JSON meta schema, adding minLength and maxLength constraints.
> CXP-1390: JSON Meta schema v0.0.5

- content/mapping/product/0.0.6/schema
New version of JSON Meta Schema for app catalogs, allowing string with format uri.
> CXP-1379: JSON Meta Schema V0.0.6

- content/mapping/product/0.0.7/schema
New version of JSON Meta Schema for app catalogs, allowing string with pattern and type dependency for minLength and maxLength
> CXP-1392: JSON Meta Schema V0.0.7

- content/mapping/product/0.0.8/schema
New version of JSON Meta Schema for app catalogs, allowing minLength and maxLength for number type
> CXP-1393: JSON Meta Schema V0.0.8

- content/mapping/product/0.0.9/schema
New version of JSON Meta Schema for app catalogs, allowing enum for number or string type
> CXP-1396: JSON Meta Schema V0.0.9

- content/mapping/product/0.0.10/schema
New version of JSON Meta Schema for app catalogs, allowing properties to be required
> CXP-1389: JSON Meta Schema V0.0.10

- content/mapping/product/0.0.12/schema
New version of JSON Meta Schema for app catalogs, allowing enum for array of strings.
> CXP-1414: JSON Meta Schema V0.0.12

- content/apps/authentication-and-authorization.md
> OCT-233: Document email_verified claim for JWT token

- content/apps/authentication-and-authorization.md
change authorization scopes link by authentication scopes link
> Update link in OpenID guide

- content/apps/overview.md
- content/apps/publish-your-app.md
> publish your app - FIX

- content/mapping/product/0.0.13/schema
New version of JSON Meta Schema for app catalogs, allowing array of string with format uri
> CXP-1385: JSON Meta Schema V0.0.13

- content/news/2023.md
> ODX-292 - Update April 2023.md

- content/rest-api/pagination.md
Coming from SDS-32206. Slack discussion here: https://akeneo.slack.com/archives/C352L4091/p1692123133887579
> SDS-32206 add info to the search_after parameter doc

- content/concepts/products.md
- content/php-client/resources/products/published-products.md
- src/api-reference/index.handlebars
- src/api-reference/reference.handlebars
- styles/alert.less
- tasks/reference.js
Display the information of deprecation in the API documentation
> CPM-1209: Published Product Deprecated

- content/news/2023.md
- styles/label.less
**What's new updates**
- Nov 2023 - Data transformation
- Oct 2023 - Published product deprecation
> Whats new updates

- content/mapping/product/0.1.0/schema
- content/mapping/product/0.2.0/schema
Added two new versions for catalogs meta-schema and updated schema example
> CXP-1660: Added new meta-schema versions to catalogs

- tasks/build-doc.js
Add the "secure your app" page to the Apps menu
> deploy: add secure your app on menu

- content/concepts/asset-manager.md
[https://akeneo.atlassian.net/browse/RAB-1784](https://akeneo.atlassian.net/browse/RAB-1784)
> Updating list of supported fields for PLRs in product selections

- content/concepts/asset-manager.md
[https://akeneo.atlassian.net/browse/RAB-1807](https://akeneo.atlassian.net/browse/RAB-1807)
> Updating doc AM - new operators & filters in PLRs

- content/concepts/products.md
- content/php-client/resources/products/published-products.md
- src/api-reference/index.handlebars
- src/api-reference/reference.handlebars
Update the message to remove the date and keep a more common message to remaining active users
> CPM-1608 : Change message for published product

- content/swagger/parameters.yaml
- content/swagger/resources/app_catalogs/routes/app_catalogs_id_product_uuids.yaml
> CHA-257: add the new parameter with_count (special catalogs for apps)

- content/graphql/queries-and-arguments.md
- content/graphql/use-cases.md
Feel free to discuss the few reformulations I did.
> CHA-530: Fix some typos

- content/graphql/queries-and-arguments.md
https://akeneo.atlassian.net/browse/CHA-527
> CHA-527 [GraphQL] fix bug on page arg

- content/graphql/limitations.md
- content/graphql/queries-and-arguments.md
Add documentation about the asset limitations
> [CPM-754] GraphQL - Add documentation about the asset limitations

- content/akeneo-event-platform/concepts.md
> CHA-781 - AEP GA - Concept page : retry policies

- content/akeneo-event-platform/concepts.md
> CHA-781 APE GA concept page - Event

- content/apps/authentication-and-authorization.md
> CHA-793-2: add delete_categories scope in the list of scopes

- content/akeneo-event-platform/platform-usage-requirements.md
> CHA-786: fill the platform usage requirements

- content/graphql/getting-started.md
> [CHA-833] GraphQL fix typo on the getting started

- content/akeneo-event-platform/available-events.md
- content/akeneo-event-platform/getting-started.md
https://akeneo.atlassian.net/browse/CHA-785
https://pr-929.api-dev.akeneo.com/akeneo-event-platform/available-events.html
> CHA-785: Available events

- content/akeneo-event-platform/concepts.md
- add best practice paragraph
- add content
> enhance concepts page with new behavior

- content/supplier-data-manager/common-usage.md
- content/supplier-data-manager/getting-started.md
- gulpfile.js
- src/partials/layout.handlebars
- src/partials/supplier-data-manager-documentation.handlebars
- tasks/build-doc.js
> dev-4330: add Supplier Data Manager API doc

- content/akeneo-event-platform/platform-usage-requirements.md
Ticket: https://akeneo.atlassian.net/browse/CHA-951
> CHA-951: Add dedicated section on event platform authorization

- content/supplier-data-manager/api-reference.md
- src/partials/layout.handlebars
- tasks/build-doc.js
Add a page that links our swagger and redoc doc.
> Add API reference

- content/event-platform/api-reference.md
- content/event-platform/getting-started.md
- use production links
- add redocly HTML API reference (not yet available, but will be deployed soon)
> add production links for assets

- content/event-platform/concepts.md
> CHA-1017 - add precision on the CE message mode

- content/supplier-data-manager/getting-started.md
- Specify that to use SDM API you need an SDM
- Fair usage
> SDM API: round #2

- content/event-platform/available-events.md
Update the documentation to reflect the latest changes on the events payload.
https://pr-976.api-dev.akeneo.com/event-platform/available-events.html
Ticket: https://akeneo.atlassian.net/browse/CHA-1097
> [CHA-1097][EP] Update available events (add author payload)

- src/index.handlebars
Change PIM sandbox explanation on the homepage
> Clean-api-doc-01: Update homepage

- src/index.handlebars
- styles/code.less
- styles/forms.less
- styles/panel.less
- styles/variables.less
Fix some issues with the new colors
> Design fixes

- src/index.handlebars
- styles/button.less
- styles/jumbotron.less
- styles/typography.less
- styles/variables.less
Design fixes from Jocelyn's feedback
> Design fixes 2

- src/index.handlebars
Update the way we introduce Events and Connectors on the Homepage
> Update Homepage content

- content/event-platform/available-events.md
- content/news/2024.md
Add `com.akeneo.pim.v1.product.updated.delta` in the doc.
https://pr-981.api-dev.akeneo.com/event-platform/available-events.html#comakeneopimv1productupdateddelta
TODO:
- Add a toggle payload visibility :heavy_check_mark: 
- Add an entry in "What's New?" :heavy_check_mark: (to improve)
- Fix the length of "com.akeneo.pim.v1.product.updated.delta" in the menu (causes scrollbar apparition) :heavy_check_mark:
> Add "product delta" documentation

- content/app-portal/manage-app-availability.md
- content/apps/authentication-and-authorization.md
- content/apps/catalogs.md
- content/apps/create-custom-app.md
- content/apps/overview.md
- content/getting-started/from-identifiers-to-uuid-7x/welcome.md
- content/getting-started/synchronize-pim-products-6x/welcome.md
- content/guides/ecommerce-connection/step2-understand-akeneo-pim.md
- content/guides/ecommerce-connection/step3-reconcile-PIM-data-with-eCommerce-data.md
- content/guides/erp-connection/step3-understand-akeneo-pim.md
- content/guides/print-connection/step2-understand-akeneo-pim.md
- content/guides/syndication-connection/step2-understand-akeneo-pim.md
- content/guides/translation-connection/step2-understand-akeneo-pim.md
- content/tutorials/guides/how-to-get-your-app-token.md
- title-description.json
- Change the way a partner can contact us
- Introduce our new training course
- Introduce GraphQL and Event Platform
- Remove PIM versions documentation in guides
- Remove Scalability PIM
- Remove App certification
> Remove deprecated contents

- .gitleaks.toml
- content/rest-api/authentication.md
- content/rest-api/authentication_old.md
- content/rest-api/overview.md
- src/partials/layout.handlebars
- styles/nav.less
Add Ref API sub-menu
Remove old versions
Improve sub-menu navigation
> Navigation modification

- content/apps/overview.md
- content/rest-api/authentication.md
- src/partials/layout.handlebars
> Quick fix on the event platform sub navigation

- content/rest-api/troubleshooting.md
Document the read after write eventual consistency.
> Add read after write eventual consistency content in rest API troubleshooting section

- src/partials/layout.handlebars
End of the Kapa experiment: Remove Kapa
> Remove Kapa

- content/concepts/asset-manager.md
- content/concepts/products.md
- content/swagger/resources/asset_families/definitions/asset_family.yaml
- content/swagger/resources/assets/definitions/asset.yaml
- content/swagger/resources/assets/routes/assets.yaml
https://akeneo.atlassian.net/browse/SA-250
https://pr-1008.api-dev.akeneo.com/
> SA-250: Add share links for every asset media file attribute

- content/event-platform/concepts.md
Just add a small example to clarify this process.
Ticket: https://akeneo.atlassian.net/browse/CHA-1332
> [CHA-1332] Add a code example on signature validation

- content/graphql/limitations.md
To merge after https://github.com/akeneo/graphql/pull/414
> [CHA-1333] GraphQL: "categories" query max depth was increased

- deployments/modules/services/networking/load-balancer.tf
This PR fix the PR concurrency on SSL policy by adding the context to the ssl policy name.
> PIM-12026 Fix PR concurrency on ssl policy

- content/event-platform/available-filters.md
- content/event-platform/concepts.md
- src/partials/layout.handlebars
Added an "available filters" section, and a note on "subscriptions" ("concepts").
https://pr-1027.api-dev.akeneo.com/event-platform/concepts.html#subscriptions-filters
https://pr-1027.api-dev.akeneo.com/event-platform/available-filters.html
TODO - Add "available filters" entry in the menu.
> [CHA-1401] Document the filters (EP Filtering)

- tasks/build-doc.js
> EP Filters: Add missing menu entry for available filters

- content/event-platform/available-events.md
> Add event for workflow task creation

- content/rest-api/filter.md
> CEX-682: add doc for task_uuids filter

- content/event-platform/available-filters.md
https://akeneo.atlassian.net/browse/CHA-1612
> CHA-1616: Update documentation with new filters parameters and new operator

- content/rest-api/filter.md
> CEX-709 fix(docs): remove NOT IN operators on list workflow tasks endpoint

- content/graphql/common-notions.md
> CHA-1626: add sentence to explain that last page can be empty

- content/files/Akeneo PIM API.postman_collection.json
> CEX-751 add workflow endpoints to postman collection

- content/event-platform/available-filters.md
cf. https://github.com/akeneo/event-platform/pull/500
> [CHA-1598] EP: document the new `user_type` filter
